name: Terraform workflows
on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_DB_USERNAME: ${{ secrets.DB_USERNAME }}
      TF_VAR_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      TF_VAR_DB_NAME: ${{ secrets.DB_NAME }}
      TF_VAR_DB_PORT: ${{ secrets.DB_PORT }}
    steps:
    # Common
    - name: Checkout
      uses: actions/checkout@v3.0.1
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.0
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
    - name: Terraform init
      run: terraform init -input=false
    # Merge Workflow
    - name: Terraform apply
      run: terraform apply -auto-approve -input=false
